// <auto-generated />
namespace Controlle_de_Senha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataHora_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataHora_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201710101856230_DataHora_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
